seed: 42

data:
  # dataset: mirabest_fits
  dataset: crumb_fits
  batch_size: 8
  input_size: 150

model:
  embedding_dim: 256

training:
  # tuned params
  learning_rate: 9.047404010598482e-05
  label_dropout: 0.11956635677389038
  weight_decay: 0.0007254860307195132

  epochs: 200
  num_train_timesteps: 1000

  eval_interval: 10
  eval_num_samples: 64

optimization:
  max_trials: 25
  parameters:
    learning_rate: { min: 0.000001, max: 0.0001, log: true }
    label_dropout: { min: 0.05, max: 0.30 }
    weight_decay: { min: 0.0001, max: 0.1, log: true }
    embedding_dim: { choices: [128, 256, 512] }
