"""Run the CRUMB-trained VQ-VAE on FITS images generated by the
EDM baseline model, to see how it reconstructs synthetic
(rather than real) radio galaxy images.
"""
import argparse
import os
import re

import numpy as np
import matplotlib.pyplot as plt

from metrics_utils import basic_MSE, score_NCC
from vq_vae_modified import get_vqvae
from fits_normalize import load_fits_stats, load_and_normalise_fits

EDM_FITS_DIR = os.path.join(
    os.path.dirname(__file__), "..", "classifier-guided-physics-informed-diffusion",
    "results", "edm_baseline",
    "20260901_191251_untagged_900926", "generated_fits",
)
# Real FITS dir, source of the cached normalisation stats (fits_stats.json)
# the diffusion model itself was trained/denormalised against, and the same
# dir train_crumb_vqvae.py's --fits-dir must point at -- reused here so
# generated images are scored on the same scale as the training script.
CRUMB_FITS_DIR = os.path.join(
    os.path.dirname(__file__), "..", "classifier-guided-physics-informed-diffusion",
    "src", "datasets", "crumb", "fits",
)
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output", "edm_outputs")

IMG_DIM = 128
LATENT_DIM = 16
NUM_EMBEDDINGS = 256


def plot_reconstructions(originals, reconstructions, filenames, out_path):
    n = len(originals)
    fig, axes = plt.subplots(n, 2, figsize=(4, 2 * n))
    for i in range(n):
        axes[i, 0].imshow(originals[i, :, :, 0] / 2 + 0.5, cmap="viridis")
        axes[i, 0].set_ylabel(filenames[i], fontsize=6)
        axes[i, 0].set_xticks([])
        axes[i, 0].set_yticks([])
        axes[i, 1].imshow(reconstructions[i, :, :, 0] / 2 + 0.5, cmap="viridis")
        axes[i, 1].set_xticks([])
        axes[i, 1].set_yticks([])
    axes[0, 0].set_title("EDM-generated")
    axes[0, 1].set_title("VQ-VAE Reconstruction")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


FINAL_PATTERN = re.compile(r"^generated_class\d+_\d+\.fits$")
EPOCH_PATTERN = re.compile(r"^generated_class\d+_\d+_(\d+)\.fits$")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--epoch", type=int, default=None,
        help="Select a specific training-epoch snapshot (e.g. generated_class0_000_250.fits). "
             "Default: use the final generated images (no epoch suffix).",
    )
    parser.add_argument("--fits-dir", default=EDM_FITS_DIR,
                         help="Directory of EDM-generated FITS files to evaluate.")
    parser.add_argument("--stats-dir", default=CRUMB_FITS_DIR,
                         help="Real FITS directory providing the cached fits_stats.json "
                              "normalisation stats, and whose basename selects the "
                              "matching vqvae_<dataset>.weights.h5. Must be the same "
                              "directory used with train_crumb_vqvae.py's --fits-dir.")
    args = parser.parse_args()

    dataset_name = os.path.basename(os.path.normpath(os.path.dirname(args.stats_dir)))
    weights_path = os.path.join(os.path.dirname(__file__), "output", f"vqvae_{dataset_name}.weights.h5")

    all_files = os.listdir(args.fits_dir)
    if args.epoch is not None:
        filenames = sorted(f for f in all_files if EPOCH_PATTERN.match(f) and EPOCH_PATTERN.match(f).group(1) == str(args.epoch))
        if not filenames:
            raise SystemExit(f"No files matching *_{args.epoch}.fits in {args.fits_dir}")
        label = f"epoch {args.epoch}"
    else:
        filenames = sorted(f for f in all_files if FINAL_PATTERN.match(f))
        if not filenames:
            raise SystemExit(f"No final (non-epoch-suffixed) generated_class*.fits files in {args.fits_dir}")
        label = "final"
    print(f"Loading {len(filenames)} EDM-generated images from {args.fits_dir} ({label})")

    noise_rms, peak_log = load_fits_stats(args.stats_dir)
    images = load_and_normalise_fits(filenames, args.fits_dir, IMG_DIM, noise_rms, peak_log)

    print(f"Loading VQ-VAE weights from {weights_path}")
    autoencoder = get_vqvae(latent_dim=LATENT_DIM, num_embeddings=NUM_EMBEDDINGS)
    autoencoder.load_weights(weights_path)

    reconstructions = autoencoder.predict(images)

    mse_scores = np.array([basic_MSE(reconstructions[i, :, :, 0], images[i, :, :, 0]) for i in range(len(images))])
    ncc_scores = np.array([score_NCC(reconstructions[i, :, :, 0], images[i, :, :, 0]) for i in range(len(images))])

    summary = (
        f"EDM-generated set: {len(images)} images ({label})\n"
        f"MSE: mean={mse_scores.mean():.6f} std={mse_scores.std():.6f}\n"
        f"NCC: mean={ncc_scores.mean():.4f} std={ncc_scores.std():.4f}\n"
    )
    print(summary)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    with open(os.path.join(OUTPUT_DIR, "edm_reconstruction_metrics.txt"), "w") as f:
        f.write(summary)
        for fn, mse, ncc in zip(filenames, mse_scores, ncc_scores):
            f.write(f"{fn}\tMSE={mse:.6f}\tNCC={ncc:.4f}\n")

    plot_reconstructions(
        images,
        reconstructions,
        filenames,
        os.path.join(OUTPUT_DIR, "edm_reconstructions.png"),
    )
    print(f"Saved plot and metrics to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
